### ISSUE TITLE
psutil issues on Raspberry Pi 

### ISSUE THREAD

**Issue by dave-malone** [aws-samples/aws-iot-device-defender-agent-sdk-python#9]
I've followed the instructions to deploy this function to a Greengrass Core running on a Rasperry Pi, and I'm seeing an issue in my logs:

`[2018-12-12T16:09:58.94Z][FATAL]-lambda_runtime.py:356,Failed to initialize Lambda runtime due to exception: cannot import name _psutil_linux`

This message is showing up in `/greengrass/ggc/var/log/user/us-east-1/myaccountid/greengrass_defender_metrics_lambda.log`. 

I've tried re-installing psutil locally, re-copied it into the metrics_lambda and then zipping a new version of the function and uploading it to the Lambda console, redeployed to the GG group, but without success. 

Based on my understanding of how this should work, the Lambda function running on the GG device should pull its dependencies from the included dependencies uploaded as part of the zip folder, but the version of psutil included does not seem to be the right version. Is this because I ran `pip install psutil` on OSX and not on a Linux machine?

**Comment by da-miller** [comment]
Hi Dave, 
Creating the package on OSX could be the cause of the issue, psutil has a platform-dependent component, since system metrics are sourced differently on OSX (ie. no _/proc_) 

So we can further investigate, can you give me a few more details about your setup:
* Raspberry Pi OS and Version
* OSX Version
* GreenGrass Core Version

As alternative to the Greengrass sample in this repo, you may want to consider a new feature that AWS Iot Greengrass recently launched called [Greengrass Connectors](https://docs.aws.amazon.com/greengrass/latest/developerguide/connectors.html). Greengrass provides a pre-built [Device Defender Connector](https://docs.aws.amazon.com/greengrass/latest/developerguide/device-defender-connector.html?icmpid=docs_gg_console) which provides the same functionality as the Greengrass Device Defender lambda sample in this repository, but with a much more streamlined deployment experience. With the Connector, you can configure and deploy  your Device Defender lambda directly through the Greengrass Management Console without having to create ZIP files and perform some of the manual steps described in the README.

**Comment by dave-malone** [comment]
Thanks for the quick response, @da-miller. I will definitely try the Greengrass Connector as well. In the meantime, here's what I'm working with:

Raspberry Pi Model 3 B+
Raspbian Jesse 
Linux raspberrypi 4.14.50-v7+ #1122 SMP Tue Jun 19 12:26:26 BST 2018 armv7l GNU/Linux
Greengrass Core version 1.7
OSX Sierra 10.12.6

**Comment by da-miller** [comment]
@dave-malone  I have reproduced the error you were getting in your lamba, and the cause is as you expected, psutil installed on a mac is not portable to a raspberry pi (or linux). The most straight-forward way to work arount this would be perform the [Create Your Lambda Package](https://github.com/aws-samples/aws-iot-device-defender-agent-sdk-python#create-your-lambda-package) steps on the platform you'd like to run the lambda on. psutil makes use of a platform-specific binary extension, which gets compiled when you install the package.  I'll update the README documentation to indicate this.
